### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/produto/10 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1

content-type: application/json
{
    "nome" : "Abc da Silva",
    "descricao" : "Teste",
    "foto" : "0519541386aed80835bc4556913f0ab12144404c74e411d0ab0574ffeca17f28c769",
    "valor_unitario" : 1
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
content-type: application/json
{
    "nome" : "Abc da Silva",
    "descricao" : "Teste",
    "foto" : "0519541386aed80835bc4556913f0ab12144404c74e411d0ab0574ffeca17f28c769",
    "valor_unitario" : 1
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/3 HTTP/1.1